version: '3.8'
services:
  nest-api:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - environment/.env.development

  postgres:
    image: postgis/postgis:12-3.0
    container_name: pg-postgis
    restart: always
    ports:
      - 5442:5432
    env_file:
      - environment/.env.development
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: app-db
